import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import AuthProvider from '@/context/AuthProvider'
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <meta name="apple-mobile-web-app-title" content="GhostMsg" />
            </head>
            <AuthProvider>
                <body
                    className={`${geistSans.className} antialiased`}
                >
                    <main>{children}</main>
                    <Toaster />
                </body>
            </AuthProvider>
        </html>
    );
}
